apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: monster-lb
  name: monster-lb
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: monster-lb
  type: LoadBalancer
status:
  loadBalancer: {}
