#
# ArgoCD App of Apps used to deploy all Crossplane related resources to the management cluster.
# This includes the Crossplane core controller, AWS provider for Crossplane, Configuration package containing Composition, CompositeResourceDefinition and CompositeResource.
#
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wonderful-monster-workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   
spec:
  project: crossplane-project
  source:
    repoURL: https://github.com/hvgirish/platform.git
    targetRevision: HEAD
    path: environments/dev/eu-west-1/wonderful-monster/workloads
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m   
